### ISSUE TITLE
Ubuntu 10.04 error - wrong Tk default version

### ISSUE THREAD

**Issue by pandemic** [goletsa/aEncoder#1]
Welcome to aEncoder Linux Beta
Testing binaries:
Your must have installed: tk8.5, mencoder, gpac >= 0.4.4
wish:
File /usr/bin/wish exist
tclsh:
File /usr/bin/tclsh exist
mencoder:
File /usr/bin/mencoder exist
MP4Box:
File /usr/bin/MP4Box exist
subfont.ttf exist
Error in startup script: can't find package tile
    while executing
"package req tile"
    (file "aEncoder.tcl" line 544)

**Comment by pandemic** [comment]
Добрый день, хотел воспользоваться Вашей программой-но появляется следующая ошибка при установке\запуске, OC - Ubuntu 10.04

**Comment by goletsa** [comment]
В Ubuntu по какой-то причине по умолчанию Tk8.4 даже если стоит Tk8.5
В последних комитах я пофиксил этот баг: http://github.com/goletsa/aEncoder/commit/9e1bc9d5caeb3616f0cdbf2ef2dfa7c54a410d2e

В разделе Downloads лежит 0.99.4.1 версия.
