### ISSUE TITLE
Добавьте поддержку mp3

### ISSUE THREAD

**Issue by Vascom** [goletsa/aEncoder#5]
Добавьте, пожалуйста, помимо faac поддержку mp3. Например в Fedora Linux mplayer собран без поддержки faac и aEncoder выдаёт ошибку:
MPlayer was compiled without libfaac. See README or DOCS.

**Comment by goletsa** [comment]
А как вам это поможет если исходное видео может быть в формате AAC?
Для mp3 в mplayer надо просто чтото типа liblame имхо поставить.

**Comment by Vascom** [comment]
Поможет тем, что если исходный AAC, то просто его скопировать. Если не aac, то закодировать в mp3.

В целом может оно и не нужно уже. Просто пришлось пересобрать менкодер с поддержкой faac.
Раз такие проблемы с менкодером возникают, то может добавить поддержку кодирования и в мп3 для универсальности?

**Comment by goletsa** [comment]
А схавает ли андроид такое видео? 
Сделать поддержку нескольких профилей в принципе реально.
Но бороться со всеми дистрибутивами где собирают мплеер криво имхо бесполезно.

**Comment by Vascom** [comment]
В том-то и вопрос, схавает ли?..
Я для себя проблему решил, дальше вам решать - менять что-то или нет :)

**Comment by goletsa** [comment]
Ну вариант с пересобраным мплеером самый простой пока. Ибо текущие опции кодирования вполне подходят для прогрывания на андроиде. Плюс там есть тонкость в том что для разных билдов надо использовать разные опции.

**Comment by Vascom** [comment]
ОК
